### ISSUE TITLE
Git shenanigans 

### ISSUE THREAD

**Issue by alerque** [graysonarts/git-superprune#1]
I tried to build a stable release of this project, but this repo doesn't have any tags. Oops.

So then I tried to build from the crates.io hosted source tarball. That fails because the build system expects to be able to use `git describe`, but the sources are not a Git repo.

I would suggest:

1. Tagging the Git repo to match anything you `cargo publish`.
2. Setting up the build profile so it can/does work without being part of a Git repository at all and/or without `git` available at build time. Since it looks like you use *libgit2* anyway for the actual function of the app it shouldn't need to use `git` CLI tooling as a build time dependency.

**Comment by graysonarts** [comment]
Thanks for reporting this! I'm using the `git_version` crate to get the version information including git commit. I'm just implementing the fix for this error since `git_version` has a fallback version setting that I wasn't using. About to push a new release.

**Comment by graysonarts** [comment]
version `0.1.2` should be installable via `cargo` now

**Comment by alerque** [comment]
Thank you. And with that, it is now possible to package. So [here is an AUR contribution for Arch Linux](https://aur.archlinux.org/packages/git-superprune). If it picks up some popularity someday I'll move it to official repos.
